Repository THIP-TextHip/THIP-Server, pull requests merged in 2025-08, with the labels that each got.

#124 [feat] 사용자 정보 수정 api 개발
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/common/swagger/SwaggerResponseDescription.java
  src/main/java/konkuk/thip/user/adapter/in/web/UserCommandController.java
  src/main/java/konkuk/thip/user/adapter/in/web/request/UserFollowRequest.java
  src/main/java/konkuk/thip/user/adapter/in/web/request/UserUpdateRequest.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/UserJpaEntity.java
  src/main/java/konkuk/thip/user/adapter/out/mapper/UserMapper.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/UserCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/UserQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/repository/UserJpaRepository.java
  src/main/java/konkuk/thip/user/application/port/in/UserUpdateUseCase.java
  src/main/java/konkuk/thip/user/application/port/in/dto/UserUpdateCommand.java
  src/main/java/konkuk/thip/user/application/port/out/UserCommandPort.java
  src/main/java/konkuk/thip/user/application/port/out/UserQueryPort.java
  src/main/java/konkuk/thip/user/application/service/UserSignupService.java
  src/main/java/konkuk/thip/user/application/service/UserUpdateService.java
  src/main/java/konkuk/thip/user/domain/User.java
  src/test/java/konkuk/thip/book/adapter/in/web/BookChangeSavedControllerTest.java
  src/test/java/konkuk/thip/book/adapter/in/web/BookDetailSearchControllerTest.java
  src/test/java/konkuk/thip/book/adapter/in/web/BookMostSearchedBooksControllerTest.java
  src/test/java/konkuk/thip/book/adapter/in/web/BookQueryControllerTest.java
  src/test/java/konkuk/thip/common/util/TestEntityFactory.java
  src/test/java/konkuk/thip/record/adapter/in/web/RecordSearchApiTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomCloseJoinApiTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomCreateAPITest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomGetMemberListApiTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomJoinApiTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomPlayingDetailViewApiTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomRecruitingDetailViewApiTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomSearchApiTest.java
  src/test/java/konkuk/thip/room/domain/RoomTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserFollowApiTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserUpdateApiTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserVerifyNicknameControllerTest.java
  src/test/java/konkuk/thip/user/application/service/UserFollowServiceTest.java
  src/test/java/konkuk/thip/user/application/service/UserUpdateServiceTest.java
  src/test/java/konkuk/thip/user/domain/UserTest.java
  src/test/java/konkuk/thip/vote/adapter/in/web/VoteCreateControllerTest.java
Labels: 🛠️ feat, 🧸 현준

#129 [feat] 특정 유저의 피드 전체 조회 api 개발
  src/main/java/konkuk/thip/feed/adapter/in/web/FeedQueryController.java
  src/main/java/konkuk/thip/feed/adapter/in/web/response/FeedShowByUserResponse.java
  src/main/java/konkuk/thip/feed/adapter/out/persistence/FeedQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/feed/adapter/out/persistence/repository/FeedQueryRepository.java
  src/main/java/konkuk/thip/feed/adapter/out/persistence/repository/FeedQueryRepositoryImpl.java
  src/main/java/konkuk/thip/feed/application/mapper/FeedQueryMapper.java
  src/main/java/konkuk/thip/feed/application/port/in/FeedShowAllOfUserUseCase.java
  src/main/java/konkuk/thip/feed/application/port/in/FeedShowMineUseCase.java
  src/main/java/konkuk/thip/feed/application/port/out/FeedQueryPort.java
  src/main/java/konkuk/thip/feed/application/service/FeedShowAllOfUserService.java
  src/main/java/konkuk/thip/feed/application/service/FeedShowMineService.java
  src/test/java/konkuk/thip/feed/adapter/in/web/FeedShowSpecificUserTest.java
Labels: 🛠️ feat, 👻 성준

#138 [hotfix] 기록장 조회시 isbn 반환 / 마감임박,인기방 조회시 recruitCount 반환
  src/main/java/konkuk/thip/record/adapter/in/web/response/RecordSearchResponse.java
  src/main/java/konkuk/thip/record/application/service/RecordSearchService.java
  src/main/java/konkuk/thip/room/adapter/in/web/response/RoomGetDeadlinePopularResponse.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/repository/RoomQueryRepositoryImpl.java
  src/main/java/konkuk/thip/room/application/port/out/dto/RoomQueryDto.java
Labels: ⚡️ fix, 🧸 현준

#134 [Feat] 댓글 삭제 api 개발
  src/main/java/konkuk/thip/comment/adapter/in/web/CommentCommandController.java
  src/main/java/konkuk/thip/comment/adapter/in/web/response/CommentDeleteResponse.java
  src/main/java/konkuk/thip/comment/adapter/out/jpa/CommentJpaEntity.java
  src/main/java/konkuk/thip/comment/adapter/out/persistence/CommentCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/comment/adapter/out/persistence/CommentLikeCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/comment/adapter/out/persistence/repository/CommentJpaRepository.java
  src/main/java/konkuk/thip/comment/adapter/out/persistence/repository/CommentLikeJpaRepository.java
  src/main/java/konkuk/thip/comment/application/port/in/CommentDeleteUseCase.java
  src/main/java/konkuk/thip/comment/application/port/out/CommentCommandPort.java
  src/main/java/konkuk/thip/comment/application/port/out/CommentLikeCommandPort.java
  src/main/java/konkuk/thip/comment/application/service/CommentCreateService.java
  src/main/java/konkuk/thip/comment/application/service/CommentDeleteService.java
  src/main/java/konkuk/thip/comment/application/service/CommentLikeService.java
  src/main/java/konkuk/thip/comment/domain/Comment.java
  src/main/java/konkuk/thip/common/entity/BaseJpaEntity.java
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/common/post/CommentCountUpdatable.java
  src/main/java/konkuk/thip/common/post/service/PostHandler.java
  src/main/java/konkuk/thip/common/swagger/SwaggerResponseDescription.java
  src/main/java/konkuk/thip/feed/adapter/in/web/FeedCommandController.java
  src/main/java/konkuk/thip/feed/adapter/in/web/request/FeedUpdateRequest.java
  src/main/java/konkuk/thip/feed/adapter/out/jpa/FeedJpaEntity.java
  src/main/java/konkuk/thip/feed/domain/Feed.java
  src/main/java/konkuk/thip/record/domain/Record.java
  src/main/java/konkuk/thip/vote/domain/Vote.java
  src/test/java/konkuk/thip/comment/adapter/in/web/CommentCreateControllerTest.java
  src/test/java/konkuk/thip/comment/adapter/in/web/CommentDeleteAPITest.java
  src/test/java/konkuk/thip/comment/domain/CommentTest.java
  src/test/java/konkuk/thip/common/util/TestEntityFactory.java
  src/test/java/konkuk/thip/feed/domain/FeedTest.java
  src/test/java/konkuk/thip/record/domain/RecordTest.java
  src/test/java/konkuk/thip/vote/domain/VoteTest.java
Labels: 🍀 refactor, 🐶 희진, 🛠️ feat

#135 [feat] 단일 피드 조회 api 개발
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/common/swagger/SwaggerResponseDescription.java
  src/main/java/konkuk/thip/feed/adapter/in/web/FeedQueryController.java
  src/main/java/konkuk/thip/feed/adapter/in/web/response/FeedShowSingleResponse.java
  src/main/java/konkuk/thip/feed/application/mapper/FeedQueryMapper.java
  src/main/java/konkuk/thip/feed/application/port/in/FeedShowSingleUseCase.java
  src/main/java/konkuk/thip/feed/application/service/FeedShowSingleService.java
  src/main/java/konkuk/thip/feed/domain/Feed.java
  src/test/java/konkuk/thip/feed/adapter/in/web/FeedShowSingleApiTest.java
  src/test/java/konkuk/thip/feed/adapter/in/web/FeedShowSpecificUserApiTest.java
  src/test/java/konkuk/thip/feed/domain/FeedTest.java
Labels: 🛠️ feat, 👻 성준

#146 [Refactor] 비공개 방 비밀번호 입력 검증시 반환값 수정
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/common/swagger/SwaggerResponseDescription.java
  src/main/java/konkuk/thip/room/adapter/in/web/RoomQueryController.java
  src/main/java/konkuk/thip/room/adapter/in/web/response/RoomVerifyPasswordResponse.java
  src/main/java/konkuk/thip/room/application/port/in/RoomVerifyPasswordUseCase.java
  src/main/java/konkuk/thip/room/application/service/RoomVerifyPasswordService.java
  src/main/java/konkuk/thip/room/domain/Room.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomVerifyPasswordAPITest.java
  src/test/java/konkuk/thip/room/domain/RoomTest.java
Labels: 🍀 refactor, 🐶 희진

#173 [Feat] 피드 삭제 api 개발 및 post soft delete 전략 도입
  src/main/java/konkuk/thip/comment/adapter/out/jpa/CommentJpaEntity.java
  src/main/java/konkuk/thip/comment/adapter/out/persistence/CommentCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/comment/adapter/out/persistence/repository/CommentJpaRepository.java
  src/main/java/konkuk/thip/comment/adapter/out/persistence/repository/CommentLikeJpaRepository.java
  src/main/java/konkuk/thip/comment/application/port/out/CommentCommandPort.java
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/common/swagger/SwaggerResponseDescription.java
  src/main/java/konkuk/thip/feed/adapter/in/web/FeedCommandController.java
  src/main/java/konkuk/thip/feed/adapter/out/jpa/FeedJpaEntity.java
  src/main/java/konkuk/thip/feed/adapter/out/persistence/FeedCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/feed/adapter/out/persistence/repository/Content/ContentJpaRepository.java
  src/main/java/konkuk/thip/feed/adapter/out/persistence/repository/FeedJpaRepository.java
  src/main/java/konkuk/thip/feed/adapter/out/persistence/repository/FeedTag/FeedTagJpaRepository.java
  src/main/java/konkuk/thip/feed/adapter/out/persistence/repository/SavedFeedJpaRepository.java
  src/main/java/konkuk/thip/feed/application/port/in/FeedDeleteUseCase.java
  src/main/java/konkuk/thip/feed/application/port/out/FeedCommandPort.java
  src/main/java/konkuk/thip/feed/application/service/FeedDeleteService.java
  src/main/java/konkuk/thip/feed/domain/Feed.java
  src/main/java/konkuk/thip/post/adapter/out/jpa/PostJpaEntity.java
  src/main/java/konkuk/thip/post/adapter/out/persistence/PostLikeCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/post/adapter/out/persistence/PostLikeJpaRepository.java
  src/main/java/konkuk/thip/post/application/port/out/PostLikeCommandPort.java
  src/test/java/konkuk/thip/book/adapter/in/web/BookDetailSearchControllerTest.java
  src/test/java/konkuk/thip/comment/adapter/in/web/CommentDeleteAPITest.java
  src/test/java/konkuk/thip/feed/adapter/in/web/FeedDeleteAPITest.java
  src/test/java/konkuk/thip/feed/domain/FeedTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomPlayingDetailViewApiTest.java
  src/test/java/konkuk/thip/vote/adapter/in/web/VoteCreateControllerTest.java
Labels: 🐶 희진, 🛠️ feat

#187 [hotfix] 모임홈 진행중인 내모임방 조회 시 책 제목이 아닌 방제목 반환 하도록 수정
  src/main/java/konkuk/thip/room/adapter/in/web/response/RoomGetHomeJoinedListResponse.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/repository/RoomQueryRepositoryImpl.java
Labels: 🐶 희진, 🔥 hotfix

#190 [hotfix] 기록장 조회 api에서 총평 가능 여부 플래그 반환
  src/main/java/konkuk/thip/record/adapter/in/web/response/RecordSearchResponse.java
  src/main/java/konkuk/thip/record/application/service/RecordSearchService.java
Labels: 🧸 현준, 🔥 hotfix

#193 [refactor] alias 응답시 aliasColor 도 같이 반환하도록 수정 + 필요한 사진 데이터 추가
  src/main/java/konkuk/thip/ThipServerApplication.java
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/common/ymlProperties/AwsS3Properties.java
  src/main/java/konkuk/thip/config/AwsS3ImageUrlInitializer.java
  src/main/java/konkuk/thip/feed/adapter/in/web/response/FeedShowAllResponse.java
  src/main/java/konkuk/thip/feed/adapter/in/web/response/FeedShowSingleResponse.java
  src/main/java/konkuk/thip/feed/adapter/out/persistence/repository/FeedQueryRepositoryImpl.java
  src/main/java/konkuk/thip/feed/application/mapper/FeedQueryMapper.java
  src/main/java/konkuk/thip/room/domain/Category.java
  src/main/java/konkuk/thip/user/adapter/in/web/response/UserProfileResponse.java
  src/main/java/konkuk/thip/user/adapter/in/web/response/UserViewAliasChoiceResponse.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/repository/alias/AliasQueryRepositoryImpl.java
  src/main/java/konkuk/thip/user/application/port/in/dto/UserViewAliasChoiceResult.java
  src/main/java/konkuk/thip/user/application/service/UserMyPageService.java
  src/main/java/konkuk/thip/user/domain/Alias.java
  src/main/java/konkuk/thip/vote/adapter/in/web/response/DummyResponse.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomRecruitingDetailViewApiTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserViewAliasChoiceControllerTest.java
Labels: 🍀 refactor, 👻 성준

#202 [deploy] 운영서버로 배포
  src/main/java/konkuk/thip/comment/adapter/in/web/response/CommentForSinglePostResponse.java
  src/main/java/konkuk/thip/comment/application/mapper/CommentQueryMapper.java
  src/main/java/konkuk/thip/room/adapter/in/web/response/RoomGetMemberListResponse.java
  src/main/java/konkuk/thip/room/application/service/RoomGetMemberListService.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomGetMemberListApiTest.java
Labels: 🧸 현준, 🚀 deploy

#203 [deploy] 쿠키 설정 배포
  src/main/java/konkuk/thip/common/security/constant/AuthParameters.java
  src/main/java/konkuk/thip/common/security/oauth2/CustomSuccessHandler.java
Labels: 🚀 deploy

#207 [deploy] 운영 서버 배포
  src/main/java/konkuk/thip/common/security/constant/AuthParameters.java
  src/main/java/konkuk/thip/common/security/oauth2/CustomSuccessHandler.java
Labels: 🚀 deploy

#195 [feat] 피드 작성을 위한 화면 조회 api 및 기록을 피드에 핀하기 api 개발
  src/main/java/konkuk/thip/book/application/service/BookSavedService.java
  src/main/java/konkuk/thip/comment/application/service/CommentDeleteService.java
  src/main/java/konkuk/thip/comment/application/service/CommentLikeService.java
  src/main/java/konkuk/thip/common/swagger/SwaggerResponseDescription.java
  src/main/java/konkuk/thip/feed/adapter/in/web/FeedQueryController.java
  src/main/java/konkuk/thip/feed/adapter/in/web/response/FeedShowWriteInfoResponse.java
  src/main/java/konkuk/thip/feed/adapter/out/persistence/FeedQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/feed/adapter/out/persistence/repository/FeedQueryRepository.java
  src/main/java/konkuk/thip/feed/adapter/out/persistence/repository/FeedQueryRepositoryImpl.java
  src/main/java/konkuk/thip/feed/application/mapper/FeedQueryMapper.java
  src/main/java/konkuk/thip/feed/application/port/in/FeedShowWriteInfoUseCase.java
  src/main/java/konkuk/thip/feed/application/port/in/dto/TagsWithCategoryResult.java
  src/main/java/konkuk/thip/feed/application/port/out/FeedQueryPort.java
  src/main/java/konkuk/thip/feed/application/port/out/dto/TagCategoryQueryDto.java
  src/main/java/konkuk/thip/feed/application/service/FeedDeleteService.java
  src/main/java/konkuk/thip/feed/application/service/FeedSavedService.java
  src/main/java/konkuk/thip/feed/application/service/FeedShowWriteInfoService.java
  src/main/java/konkuk/thip/post/application/service/PostLikeService.java
  src/main/java/konkuk/thip/record/adapter/in/web/RecordQueryController.java
  src/main/java/konkuk/thip/record/adapter/in/web/response/RecordPinResponse.java
  src/main/java/konkuk/thip/record/application/port/in/RecordPinUseCase.java
  src/main/java/konkuk/thip/record/application/port/in/dto/RecordPinQuery.java
  src/main/java/konkuk/thip/record/application/service/RecordCreateService.java
  src/main/java/konkuk/thip/record/application/service/RecordDeleteService.java
  src/main/java/konkuk/thip/record/application/service/RecordPinService.java
  src/main/java/konkuk/thip/record/domain/Record.java
  src/test/java/konkuk/thip/feed/adapter/in/web/FeedShowWriteInfoAPITest.java
  src/test/java/konkuk/thip/record/adapter/in/web/RecordPinAPITest.java
  src/test/java/konkuk/thip/record/domain/RecordTest.java
Labels: 🐶 희진, 🛠️ feat

#183 [refactor] 방 생성, 투표 생성 api 수정
  src/main/java/konkuk/thip/record/application/service/RecordCreateService.java
  src/main/java/konkuk/thip/room/application/service/RoomCreateService.java
  src/main/java/konkuk/thip/room/application/service/RoomJoinService.java
  src/main/java/konkuk/thip/room/domain/RoomParticipant.java
  src/main/java/konkuk/thip/roompost/application/service/helper/RoomProgressHelper.java
  src/main/java/konkuk/thip/vote/application/service/VoteCreateService.java
  src/main/java/konkuk/thip/vote/domain/VoteItem.java
  src/test/java/konkuk/thip/common/util/TestEntityFactory.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomCreateAPITest.java
  src/test/java/konkuk/thip/room/application/service/RoomJoinServiceTest.java
  src/test/java/konkuk/thip/vote/adapter/in/web/VoteCreateApiTest.java
  src/test/java/konkuk/thip/vote/adapter/in/web/VoteCreateControllerTest.java
  src/test/java/konkuk/thip/vote/application/service/VoteCreateServiceTest.java
Labels: 🍀 refactor, 👻 성준

#226 [refactor] 기록장 조회 api 리팩토링
  Dockerfile
  src/main/java/konkuk/thip/record/adapter/in/web/response/RecordSearchResponse.java
  src/main/java/konkuk/thip/record/adapter/out/persistence/repository/RecordQueryRepositoryImpl.java
  src/main/java/konkuk/thip/record/application/mapper/RecordQueryMapper.java
  src/main/java/konkuk/thip/record/application/service/RecordSearchService.java
  src/main/java/konkuk/thip/record/application/service/validator/RecordAccessValidator.java
Labels: 🍀 refactor, 🧸 현준

#239 [hotfix] 개발된 모든 api의 response inner class 네이밍 수정
  src/main/java/konkuk/thip/book/adapter/in/web/response/BookRecruitingRoomsResponse.java
  src/main/java/konkuk/thip/book/adapter/in/web/response/BookSearchListResponse.java
  src/main/java/konkuk/thip/book/application/mapper/BookQueryMapper.java
  src/main/java/konkuk/thip/feed/adapter/in/web/response/FeedShowAllResponse.java
  src/main/java/konkuk/thip/feed/adapter/in/web/response/FeedShowByUserResponse.java
  src/main/java/konkuk/thip/feed/adapter/in/web/response/FeedShowMineResponse.java
  src/main/java/konkuk/thip/feed/application/mapper/FeedQueryMapper.java
  src/main/java/konkuk/thip/feed/application/service/BasicFeedShowAllService.java
  src/main/java/konkuk/thip/feed/application/service/FeedShowAllOfUserService.java
  src/main/java/konkuk/thip/feed/application/service/FollowingPriorityFeedShowAllService.java
  src/main/java/konkuk/thip/room/adapter/in/web/response/RoomGetDeadlinePopularResponse.java
  src/main/java/konkuk/thip/room/application/mapper/RoomQueryMapper.java
  src/main/java/konkuk/thip/roompost/adapter/in/web/response/RoomPostSearchResponse.java
  src/main/java/konkuk/thip/roompost/application/mapper/RoomPostQueryMapper.java
  src/main/java/konkuk/thip/roompost/application/service/RoomPostSearchService.java
  src/main/java/konkuk/thip/user/adapter/in/web/response/UserSearchResponse.java
  src/main/java/konkuk/thip/user/adapter/in/web/response/UserSignupResponse.java
  src/main/java/konkuk/thip/user/application/mapper/UserQueryMapper.java
Labels: 👻 성준, 🔥 hotfix

#238 [Hotfix] 댓글 생성시 댓글 조회와 같은 형식으로 response 반환
  src/main/java/konkuk/thip/comment/adapter/in/web/CommentCommandController.java
  src/main/java/konkuk/thip/comment/adapter/in/web/response/CommentCreateResponse.java
  src/main/java/konkuk/thip/comment/adapter/in/web/response/CommentIdResponse.java
  src/main/java/konkuk/thip/comment/adapter/out/persistence/CommentQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/comment/adapter/out/persistence/repository/CommentQueryRepository.java
  src/main/java/konkuk/thip/comment/adapter/out/persistence/repository/CommentQueryRepositoryImpl.java
  src/main/java/konkuk/thip/comment/application/mapper/CommentQueryMapper.java
  src/main/java/konkuk/thip/comment/application/port/in/CommentCreateUseCase.java
  src/main/java/konkuk/thip/comment/application/port/out/CommentQueryPort.java
  src/main/java/konkuk/thip/comment/application/service/CommentCreateService.java
Labels: 🐶 희진, 🔥 hotfix

#245 [chore] 소셜 로그인 수정
  src/main/java/konkuk/thip/common/security/constant/AuthParameters.java
  src/main/java/konkuk/thip/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/konkuk/thip/common/security/oauth2/CustomSuccessHandler.java
  src/main/java/konkuk/thip/common/security/oauth2/auth/AuthController.java
  src/main/java/konkuk/thip/config/SecurityConfig.java
Labels: 🧹 chore, 🧸 현준

#267 [Feat] 방 나가기 api 개발
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/common/swagger/SwaggerResponseDescription.java
  src/main/java/konkuk/thip/room/adapter/in/web/RoomCommandController.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/RoomJpaEntity.java
  src/main/java/konkuk/thip/room/application/port/in/RoomParticipantDeleteUseCase.java
  src/main/java/konkuk/thip/room/application/port/out/RoomParticipantCommandPort.java
  src/main/java/konkuk/thip/room/application/service/RoomParticipantDeleteService.java
  src/main/java/konkuk/thip/room/domain/RoomParticipant.java
  src/main/java/konkuk/thip/roompost/application/service/RecordCreateService.java
  src/main/java/konkuk/thip/roompost/application/service/RecordDeleteService.java
  src/main/java/konkuk/thip/roompost/application/service/VoteCreateService.java
  src/main/java/konkuk/thip/roompost/application/service/VoteDeleteService.java
  src/main/java/konkuk/thip/roompost/application/service/manager/RoomProgressManager.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomParticipantDeleteApiTest.java
  src/test/java/konkuk/thip/room/domain/RoomParticipantTest.java
Labels: 🐶 희진, 🛠️ feat

#271 [chore] main 브랜치에 바로 적용한 hotfix 변경사항 develop 브랜치 에도 적용
  src/main/java/konkuk/thip/room/adapter/out/persistence/repository/RoomQueryRepositoryImpl.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomShowMineApiTest.java
Labels: 🧹 chore, 👻 성준

#273 [test] 테스트 커버리지 측정 도입
  build.gradle
  jacoco.gradle
Labels: ⚠️ test, 🧸 현준

#278 [feat] 오늘의 한마디 삭제 api 개발
  src/main/java/konkuk/thip/TestTokenController.java
  src/main/java/konkuk/thip/common/entity/BaseJpaEntity.java
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/common/swagger/SwaggerResponseDescription.java
  src/main/java/konkuk/thip/config/SecurityConfig.java
  src/main/java/konkuk/thip/post/adapter/out/jpa/PostJpaEntity.java
  src/main/java/konkuk/thip/roompost/adapter/in/web/RoomPostCommandController.java
  src/main/java/konkuk/thip/roompost/adapter/in/web/response/AttendanceCheckDeleteResponse.java
  src/main/java/konkuk/thip/roompost/adapter/out/jpa/AttendanceCheckJpaEntity.java
  src/main/java/konkuk/thip/roompost/adapter/out/persistence/AttendanceCheckCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/roompost/adapter/out/persistence/repository/attendancecheck/AttendanceCheckJpaRepository.java
  src/main/java/konkuk/thip/roompost/application/port/in/AttendanceCheckDeleteUseCase.java
  src/main/java/konkuk/thip/roompost/application/port/out/AttendanceCheckCommandPort.java
  src/main/java/konkuk/thip/roompost/application/service/AttendanceCheckDeleteService.java
  src/main/java/konkuk/thip/roompost/application/service/RoomPostUpdateService.java
  src/main/java/konkuk/thip/roompost/domain/AttendanceCheck.java
  src/test/java/konkuk/thip/roompost/adapter/in/web/AttendanceCheckDeleteApiTest.java
  src/test/java/konkuk/thip/roompost/domain/AttendanceCheckTest.java
Labels: 🛠️ feat, 👻 성준
