Repository THIP-TextHip/THIP-Server, pull requests merged in 2025-06, with the labels that each got.

#13 [chore] JPA entity 작성
  src/main/java/konkuk/thip/book/adapter/out/jpa/BookJpaEntity.java
  src/main/java/konkuk/thip/book/adapter/out/jpa/CategoryJpaEntity.java
  src/main/java/konkuk/thip/comment/adapter/out/jpa/CommentJpaEntity.java
  src/main/java/konkuk/thip/comment/adapter/out/jpa/CommentLikeJpaEntity.java
  src/main/java/konkuk/thip/feed/adapter/out/jpa/FeedJpaEntity.java
  src/main/java/konkuk/thip/feed/adapter/out/jpa/TagJpaEntity.java
  src/main/java/konkuk/thip/global/entity/BaseJpaEntity.java
  src/main/java/konkuk/thip/global/entity/JpaEntityStatus.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/ContentJpaEntity.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/PostJpaEntity.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/PostLikeJpaEntity.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/RecordJpaEntity.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/RoomJpaEntity.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/VoteItemJpaEntity.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/VoteJpaEntity.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/AliasJpaEntity.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/AttendanceCheckJpaEntity.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/AttendanceCheckJpaEntityId.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/FollowingJpaEntity.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/FollowingJpaEntityId.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/NotificationJpaEntity.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/RecentSearchJpaEntity.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/SavedBookJpaEntity.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/SavedFeedJpaEntity.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/SearchType.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/UserJpaEntity.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/UserRole.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/UserRoomJpaEntity.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/UserRoomJpaEntityId.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/UserRoomRole.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/UserVoteJpaEntity.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/UserVoteJpaEntityId.java
Labels: 🧹 chore, 🐶 희진

#33 [feat] 책 검색 api 개발
  src/main/java/konkuk/thip/book/adapter/in/web/BookQueryController.java
  src/main/java/konkuk/thip/book/adapter/in/web/request/DummyRequest.java
  src/main/java/konkuk/thip/book/adapter/in/web/response/GetBookSearchListResponse.java
  src/main/java/konkuk/thip/book/adapter/out/api/BookApiAdapter.java
  src/main/java/konkuk/thip/book/adapter/out/api/NaverApiUtil.java
  src/main/java/konkuk/thip/book/adapter/out/api/NaverBookXmlParser.java
  src/main/java/konkuk/thip/book/adapter/out/api/dto/NaverBookParseResult.java
  src/main/java/konkuk/thip/book/application/port/in/BookSearchUseCase.java
  src/main/java/konkuk/thip/book/application/port/in/DummyUseCase.java
  src/main/java/konkuk/thip/book/application/port/out/SearchBookQueryPort.java
  src/main/java/konkuk/thip/book/application/service/BookSearchService.java
  src/main/java/konkuk/thip/book/application/service/BookService.java
  src/main/java/konkuk/thip/common/dto/ErrorResponse.java
  src/main/java/konkuk/thip/common/exception/BusinessException.java
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/test/java/konkuk/thip/book/adapter/in/web/BookQueryControllerTest.java
  src/test/java/konkuk/thip/book/adapter/out/api/NaverApiUtilTest.java
Labels: 🐶 희진, 🛠️ feat

#35 [feat] 닉네임 중복 검사, 칭호 선택 view api 개발
  build.gradle
  src/main/java/konkuk/thip/config/QuerydslConfig.java
  src/main/java/konkuk/thip/user/adapter/in/web/UserCommandController.java
  src/main/java/konkuk/thip/user/adapter/in/web/UserQueryController.java
  src/main/java/konkuk/thip/user/adapter/in/web/request/PostUserSignupRequest.java
  src/main/java/konkuk/thip/user/adapter/in/web/request/PostUserVerifyNicknameRequest.java
  src/main/java/konkuk/thip/user/adapter/in/web/response/GetUserShowAliasChoiceResponse.java
  src/main/java/konkuk/thip/user/adapter/in/web/response/PostUserSignupResponse.java
  src/main/java/konkuk/thip/user/adapter/in/web/response/PostUserVerifyNicknameResponse.java
  src/main/java/konkuk/thip/user/adapter/in/web/response/UserSignupResponse.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/AliasJpaRepository.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/AliasQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/AliasQueryRepository.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/AliasQueryRepositoryImpl.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/UserJpaRepository.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/UserQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/UserQueryRepository.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/UserQueryRepositoryImpl.java
  src/main/java/konkuk/thip/user/application/port/in/ShowAliasChoiceViewUseCase.java
  src/main/java/konkuk/thip/user/application/port/in/VerifyNicknameUseCase.java
  src/main/java/konkuk/thip/user/application/port/in/dto/AliasChoiceViewResult.java
  src/main/java/konkuk/thip/user/application/port/in/dto/DummyResult.java
  src/main/java/konkuk/thip/user/application/port/out/AliasQueryPort.java
  src/main/java/konkuk/thip/user/application/port/out/UserQueryPort.java
  src/main/java/konkuk/thip/user/application/service/ShowAliasChoiceViewService.java
  src/main/java/konkuk/thip/user/application/service/VerifyNicknameService.java
  src/test/java/konkuk/thip/config/TestQuerydslConfig.java
  src/test/java/konkuk/thip/feed/adapter/out/jpa/FeedJpaEntityTest.java
  src/test/java/konkuk/thip/room/adapter/out/jpa/RecordJpaEntityTest.java
  src/test/java/konkuk/thip/room/adapter/out/jpa/RoomJpaEntityTest.java
  src/test/java/konkuk/thip/room/adapter/out/jpa/VoteJpaEntityTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/ShowAliasChoiceViewControllerTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserSignupControllerTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/VerifyNicknameControllerTest.java
  src/test/java/konkuk/thip/user/adapter/out/jpa/UserJpaEntityTest.java
Labels: 🛠️ feat, 👻 성준
