Repository THIP-TextHip/THIP-Server, pull requests merged in 2025-07, with the labels that each got.

#43 [Feat] 책 검색 시 사용자 최근 검색어 로직 추가
  src/main/java/konkuk/thip/book/adapter/in/web/BookQueryController.java
  src/main/java/konkuk/thip/book/application/port/in/BookSearchUseCase.java
  src/main/java/konkuk/thip/book/application/service/BookSearchService.java
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/recentSearch/adapter/out/jpa/SearchType.java
  src/main/java/konkuk/thip/recentSearch/adapter/out/persistence/RecentSearchCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/recentSearch/application/port/out/RecentSearchCommandPort.java
  src/test/java/konkuk/thip/book/adapter/in/web/BookQueryControllerTest.java
Labels: 🐶 희진, 🛠️ feat

#49 [Feat] 가장 많이 검색된 책 조회 api 개발 및 책 상세 검색 시 검색카운트 업데이트 로직 추가
  .github/workflows/ci-workflow.yml
  src/main/java/konkuk/thip/ThipServerApplication.java
  src/main/java/konkuk/thip/book/adapter/in/web/BookQueryController.java
  src/main/java/konkuk/thip/book/adapter/in/web/response/GetBookMostSearchResponse.java
  src/main/java/konkuk/thip/book/adapter/out/api/BookApiNaverApiAdapter.java
  src/main/java/konkuk/thip/book/adapter/out/persistence/BookJpaRepository.java
  src/main/java/konkuk/thip/book/adapter/out/persistence/BookQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/book/adapter/out/persistence/BookRedisAdapter.java
  src/main/java/konkuk/thip/book/application/port/in/BookMostSearchUseCase.java
  src/main/java/konkuk/thip/book/application/port/in/dto/BookMostSearchResult.java
  src/main/java/konkuk/thip/book/application/port/out/BookApiQueryPort.java
  src/main/java/konkuk/thip/book/application/port/out/BookQueryPort.java
  src/main/java/konkuk/thip/book/application/port/out/BookRedisCommandPort.java
  src/main/java/konkuk/thip/book/application/port/out/BookRedisQueryPort.java
  src/main/java/konkuk/thip/book/application/service/BookMostSearchRankService.java
  src/main/java/konkuk/thip/book/application/service/BookMostSearchService.java
  src/main/java/konkuk/thip/book/application/service/BookSavedService.java
  src/main/java/konkuk/thip/book/application/service/BookSearchService.java
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/config/RedisConfig.java
  src/test/java/konkuk/thip/ThipServerApplicationTests.java
  src/test/java/konkuk/thip/book/adapter/in/web/BookMostSearchedBooksControllerTest.java
  src/test/java/konkuk/thip/book/application/service/BookSearchRankServiceTest.java
Labels: 🐶 희진, 🛠️ feat

#50 [feat] 기록 생성 api 개발
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/record/adapter/in/web/RecordCommandController.java
  src/main/java/konkuk/thip/record/adapter/in/web/request/DummyRequest.java
  src/main/java/konkuk/thip/record/adapter/in/web/request/RecordCreateRequest.java
  src/main/java/konkuk/thip/record/adapter/in/web/response/DummyResponse.java
  src/main/java/konkuk/thip/record/adapter/in/web/response/RecordCreateResponse.java
  src/main/java/konkuk/thip/record/adapter/out/persistence/RecordCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/record/application/port/in/DummyUseCase.java
  src/main/java/konkuk/thip/record/application/port/in/RecordCreateUseCase.java
  src/main/java/konkuk/thip/record/application/port/in/dto/DummyCommand.java
  src/main/java/konkuk/thip/record/application/port/in/dto/RecordCreateCommand.java
  src/main/java/konkuk/thip/record/application/port/out/RecordCommandPort.java
  src/main/java/konkuk/thip/record/application/service/RecordCreateService.java
  src/main/java/konkuk/thip/record/application/service/RecordService.java
  src/main/java/konkuk/thip/record/domain/Record.java
  src/main/java/konkuk/thip/room/domain/Room.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/UserRoomCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/UserRoomJpaRepository.java
  src/main/java/konkuk/thip/user/application/port/out/UserRoomCommandPort.java
  src/main/java/konkuk/thip/user/application/port/out/UserRoomQueryPort.java
  src/main/java/konkuk/thip/user/domain/UserRoom.java
  src/main/java/konkuk/thip/vote/application/service/VoteCreateService.java
  src/test/java/konkuk/thip/book/adapter/in/web/BookChangeSavedControllerTest.java
  src/test/java/konkuk/thip/book/adapter/in/web/BookDetailSearchControllerTest.java
  src/test/java/konkuk/thip/book/adapter/in/web/BookQueryControllerTest.java
  src/test/java/konkuk/thip/book/adapter/out/api/NaverApiUtilTest.java
  src/test/java/konkuk/thip/feed/adapter/out/jpa/FeedJpaEntityTest.java
  src/test/java/konkuk/thip/record/adapter/in/web/RecordCreateControllerTest.java
  src/test/java/konkuk/thip/record/domain/RecordTest.java
  src/test/java/konkuk/thip/room/adapter/out/jpa/RecordJpaEntityTest.java
  src/test/java/konkuk/thip/room/adapter/out/jpa/RoomJpaEntityTest.java
  src/test/java/konkuk/thip/room/adapter/out/jpa/VoteJpaEntityTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserSignupControllerTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserVerifyNicknameControllerTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserViewAliasChoiceControllerTest.java
  src/test/java/konkuk/thip/user/adapter/out/jpa/UserJpaEntityTest.java
  src/test/java/konkuk/thip/user/domain/UserRoomTest.java
  src/test/java/konkuk/thip/vote/adapter/in/web/VoteCreateControllerTest.java
  src/test/java/konkuk/thip/vote/domain/VoteTest.java
Labels: 🛠️ feat, 🧸 현준

#51 [feat] 방생성 api 개발
  src/main/java/konkuk/thip/book/adapter/out/api/CompositeBookApiAdapter.java
  src/main/java/konkuk/thip/book/adapter/out/api/NaverApiClient.java
  src/main/java/konkuk/thip/book/adapter/out/api/NaverBookXmlParser.java
  src/main/java/konkuk/thip/book/adapter/out/api/aladin/AladinApiClient.java
  src/main/java/konkuk/thip/book/adapter/out/api/aladin/AladinApiParam.java
  src/main/java/konkuk/thip/book/adapter/out/api/aladin/AladinApiUtil.java
  src/main/java/konkuk/thip/book/adapter/out/jpa/BookJpaEntity.java
  src/main/java/konkuk/thip/book/adapter/out/persistence/BookCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/book/application/port/out/BookApiQueryPort.java
  src/main/java/konkuk/thip/book/application/port/out/BookCommandPort.java
  src/main/java/konkuk/thip/book/application/service/BookSavedService.java
  src/main/java/konkuk/thip/book/domain/Book.java
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/config/RestTemplateConfig.java
  src/main/java/konkuk/thip/room/adapter/in/web/RoomCommandController.java
  src/main/java/konkuk/thip/room/adapter/in/web/request/DummyRequest.java
  src/main/java/konkuk/thip/room/adapter/in/web/request/RoomCreateRequest.java
  src/main/java/konkuk/thip/room/adapter/in/web/response/DummyResponse.java
  src/main/java/konkuk/thip/room/adapter/in/web/response/RoomCreateResponse.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/RoomJpaEntity.java
  src/main/java/konkuk/thip/room/adapter/out/mapper/RoomMapper.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/CategoryCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/CategoryJpaRepository.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/RoomCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/room/application/port/in/DummyUseCase.java
  src/main/java/konkuk/thip/room/application/port/in/RoomCreateUseCase.java
  src/main/java/konkuk/thip/room/application/port/in/dto/DummyCommand.java
  src/main/java/konkuk/thip/room/application/port/in/dto/RoomCreateCommand.java
  src/main/java/konkuk/thip/room/application/port/out/CategoryCommandPort.java
  src/main/java/konkuk/thip/room/application/port/out/RoomCommandPort.java
  src/main/java/konkuk/thip/room/application/service/RoomCreateService.java
  src/main/java/konkuk/thip/room/application/service/RoomService.java
  src/main/java/konkuk/thip/room/domain/Room.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomCreateAPITest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomCreateControllerTest.java
  src/test/java/konkuk/thip/room/domain/RoomTest.java
Labels: 🛠️ feat, 👻 성준

#57 [feat] 비공개 방 비밀번호 입력 검증 api 개발
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/room/adapter/in/web/RoomQueryController.java
  src/main/java/konkuk/thip/room/adapter/in/web/request/RoomVerifyPasswordRequest.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/RoomJpaEntity.java
  src/main/java/konkuk/thip/room/application/port/in/RoomVerifyPasswordUseCase.java
  src/main/java/konkuk/thip/room/application/port/in/dto/DummyQuery.java
  src/main/java/konkuk/thip/room/application/port/in/dto/RoomVerifyPasswordQuery.java
  src/main/java/konkuk/thip/room/application/service/RoomVerifyPasswordService.java
  src/main/java/konkuk/thip/room/domain/Room.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomVerifyPasswordAPITest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomVerifyPasswordControllerTest.java
  src/test/java/konkuk/thip/room/domain/RoomTest.java
Labels: 🐶 희진, 🛠️ feat

#66 [refactor] 기록장 조회 api 수정
  src/main/java/konkuk/thip/book/adapter/out/persistence/BookCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/book/application/port/out/BookCommandPort.java
  src/main/java/konkuk/thip/common/util/DateUtil.java
  src/main/java/konkuk/thip/feed/adapter/out/jpa/FeedJpaEntity.java
  src/main/java/konkuk/thip/feed/adapter/out/mapper/FeedMapper.java
  src/main/java/konkuk/thip/feed/domain/Feed.java
  src/main/java/konkuk/thip/post/adapter/out/jpa/PostJpaEntity.java
  src/main/java/konkuk/thip/record/adapter/in/web/RecordQueryController.java
  src/main/java/konkuk/thip/record/adapter/in/web/response/RecordDto.java
  src/main/java/konkuk/thip/record/adapter/in/web/response/RecordSearchResponse.java
  src/main/java/konkuk/thip/record/adapter/in/web/response/VoteDto.java
  src/main/java/konkuk/thip/record/adapter/out/jpa/RecordJpaEntity.java
  src/main/java/konkuk/thip/record/adapter/out/mapper/RecordMapper.java
  src/main/java/konkuk/thip/record/adapter/out/persistence/RecordQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/record/adapter/out/persistence/RecordQueryRepository.java
  src/main/java/konkuk/thip/record/adapter/out/persistence/RecordQueryRepositoryImpl.java
  src/main/java/konkuk/thip/record/adapter/out/persistence/RecordSearchSortParams.java
  src/main/java/konkuk/thip/record/adapter/out/persistence/RecordSearchTypeParams.java
  src/main/java/konkuk/thip/record/application/port/in/dto/RecordSearchQuery.java
  src/main/java/konkuk/thip/record/application/port/in/dto/RecordSearchUseCase.java
  src/main/java/konkuk/thip/record/application/port/out/RecordQueryPort.java
  src/main/java/konkuk/thip/record/application/service/RecordSearchService.java
  src/main/java/konkuk/thip/record/domain/Record.java
  src/main/java/konkuk/thip/vote/adapter/out/jpa/VoteJpaEntity.java
  src/main/java/konkuk/thip/vote/adapter/out/mapper/VoteMapper.java
  src/main/java/konkuk/thip/vote/domain/Vote.java
  src/main/java/konkuk/thip/vote/domain/VoteItem.java
  src/test/java/konkuk/thip/record/adapter/in/web/RecordQueryControllerTest.java
  src/test/java/konkuk/thip/record/adapter/out/persistence/RecordQueryRepositoryImplTest.java
  src/test/java/konkuk/thip/record/application/service/RecordSearchServiceTest.java
Labels: 🍀 refactor, 🧸 현준

#67 [feat] 모집중인 방 상세보기 api 개발
  src/main/java/konkuk/thip/common/util/DateUtil.java
  src/main/java/konkuk/thip/room/adapter/in/web/RoomQueryController.java
  src/main/java/konkuk/thip/room/adapter/in/web/response/RoomRecruitingDetailViewResponse.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/CategoryJpaEntity.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/RoomQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/RoomQueryRepository.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/RoomQueryRepositoryImpl.java
  src/main/java/konkuk/thip/room/application/port/in/RoomShowRecruitingDetailViewUseCase.java
  src/main/java/konkuk/thip/room/application/port/out/RoomQueryPort.java
  src/main/java/konkuk/thip/room/application/service/RoomShowRecruitingDetailViewService.java
  src/main/java/konkuk/thip/room/domain/Category.java
  src/main/java/konkuk/thip/user/domain/RoomParticipants.java
  src/test/java/konkuk/thip/common/util/TestEntityFactory.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomRecruitingDetailViewApiTest.java
  src/test/java/konkuk/thip/user/domain/RoomParticipantsTest.java
  src/test/java/konkuk/thip/vote/adapter/in/web/VoteCreateControllerTest.java
Labels: 🛠️ feat, 👻 성준

#75 [feat] 진행중인 방 상세보기 api 개발
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/room/adapter/in/web/RoomQueryController.java
  src/main/java/konkuk/thip/room/adapter/in/web/response/RoomPlayingDetailViewResponse.java
  src/main/java/konkuk/thip/room/application/port/in/RoomShowPlayingDetailViewUseCase.java
  src/main/java/konkuk/thip/room/application/service/RoomShowPlayingDetailViewService.java
  src/main/java/konkuk/thip/user/domain/RoomParticipants.java
  src/main/java/konkuk/thip/vote/adapter/out/persistence/VoteQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/vote/adapter/out/persistence/VoteQueryRepository.java
  src/main/java/konkuk/thip/vote/adapter/out/persistence/VoteQueryRepositoryImpl.java
  src/main/java/konkuk/thip/vote/application/port/out/VoteQueryPort.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomPlayingDetailViewApiTest.java
  src/test/java/konkuk/thip/user/domain/RoomParticipantsTest.java
Labels: 🛠️ feat, 👻 성준

#76 [feat] 팔로잉 상태 변경 api 개발
  src/main/java/konkuk/thip/common/entity/BaseDomainEntity.java
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/user/adapter/in/web/UserCommandController.java
  src/main/java/konkuk/thip/user/adapter/in/web/request/UserFollowRequest.java
  src/main/java/konkuk/thip/user/adapter/in/web/response/UserFollowResponse.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/FollowingJpaEntity.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/FollowingCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/FollowingJpaRepository.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/FollowingQueryRepository.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/FollowingQueryRepositoryImpl.java
  src/main/java/konkuk/thip/user/application/port/in/UserFollowUsecase.java
  src/main/java/konkuk/thip/user/application/port/in/dto/UserFollowCommand.java
  src/main/java/konkuk/thip/user/application/port/out/FollowingCommandPort.java
  src/main/java/konkuk/thip/user/application/service/UserFollowService.java
  src/main/java/konkuk/thip/user/domain/Following.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomGetMemberListApiTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserFollowApiTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserFollowControllerTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserSignupControllerTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserVerifyNicknameControllerTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserViewAliasChoiceControllerTest.java
  src/test/java/konkuk/thip/user/application/service/UserFollowServiceTest.java
  src/test/java/konkuk/thip/user/domain/FollowingTest.java
Labels: 🛠️ feat, 🧸 현준

#87 [feat] 방 참여하기/취소하기 api 개발
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/room/adapter/in/web/RoomCommandController.java
  src/main/java/konkuk/thip/room/adapter/in/web/request/RoomJoinRequest.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/RoomJpaEntity.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/RoomParticipantJpaEntity.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/RoomParticipantRole.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/RoomCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/RoomParticipantCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/RoomParticipantQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/repository/roomparticipant/RoomParticipantJpaRepository.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/repository/roomparticipant/RoomParticipantQueryRepository.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/repository/roomparticipant/RoomParticipantQueryRepositoryImpl.java
  src/main/java/konkuk/thip/room/application/port/in/RoomJoinUsecase.java
  src/main/java/konkuk/thip/room/application/port/in/dto/RoomJoinCommand.java
  src/main/java/konkuk/thip/room/application/port/out/RoomCommandPort.java
  src/main/java/konkuk/thip/room/application/port/out/RoomParticipantCommandPort.java
  src/main/java/konkuk/thip/room/application/port/out/RoomParticipantQueryPort.java
  src/main/java/konkuk/thip/room/application/service/RoomJoinService.java
  src/main/java/konkuk/thip/room/domain/Room.java
  src/main/java/konkuk/thip/room/domain/RoomJoinType.java
  src/main/java/konkuk/thip/room/domain/RoomParticipant.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/repository/following/FollowingQueryRepository.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/repository/following/FollowingQueryRepositoryImpl.java
  src/test/java/konkuk/thip/book/adapter/in/web/BookDetailSearchControllerTest.java
  src/test/java/konkuk/thip/common/util/TestEntityFactory.java
  src/test/java/konkuk/thip/record/adapter/in/web/RecordCreateControllerTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomCreateAPITest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomGetHomeJoinedRoomsApiTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomGetMemberListApiTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomJoinApiTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomPlayingDetailViewApiTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomRecruitingDetailViewApiTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomSearchApiTest.java
  src/test/java/konkuk/thip/room/adapter/out/jpa/RoomJpaEntityTest.java
  src/test/java/konkuk/thip/room/application/service/RoomJoinServiceTest.java
  src/test/java/konkuk/thip/room/domain/RoomTest.java
Labels: 🛠️ feat, 🧸 현준

#88 [feat] 방 모집마감 api 개발
  src/main/java/konkuk/thip/book/domain/SavedBooks.java
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/record/application/service/RecordCreateService.java
  src/main/java/konkuk/thip/room/adapter/in/web/RoomCommandController.java
  src/main/java/konkuk/thip/room/adapter/in/web/request/RoomJoinRequest.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/RoomJpaEntity.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/RoomCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/RoomParticipantCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/repository/roomparticipant/RoomParticipantJpaRepository.java
  src/main/java/konkuk/thip/room/application/port/in/RoomJoinUseCase.java
  src/main/java/konkuk/thip/room/application/port/in/RoomRecruitCloseUsecase.java
  src/main/java/konkuk/thip/room/application/port/out/RoomCommandPort.java
  src/main/java/konkuk/thip/room/application/port/out/RoomParticipantCommandPort.java
  src/main/java/konkuk/thip/room/application/service/RoomGetMemberListService.java
  src/main/java/konkuk/thip/room/application/service/RoomJoinService.java
  src/main/java/konkuk/thip/room/application/service/RoomRecruitCloseService.java
  src/main/java/konkuk/thip/room/application/service/RoomShowPlayingDetailViewService.java
  src/main/java/konkuk/thip/room/application/service/RoomShowRecruitingDetailViewService.java
  src/main/java/konkuk/thip/room/application/service/RoomVerifyPasswordService.java
  src/main/java/konkuk/thip/room/domain/Room.java
  src/main/java/konkuk/thip/room/domain/RoomParticipant.java
  src/main/java/konkuk/thip/user/application/service/following/UserFollowService.java
  src/main/java/konkuk/thip/vote/application/service/VoteCreateService.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomCloseJoinApiTest.java
  src/test/java/konkuk/thip/room/application/service/RoomJoinServiceTest.java
  src/test/java/konkuk/thip/room/domain/RoomTest.java
  src/test/java/konkuk/thip/user/application/service/UserFollowServiceTest.java
Labels: 🛠️ feat, 🧸 현준

#101 [feat] 댓글 작성 api 개발
  src/main/java/konkuk/thip/comment/adapter/in/web/CommentCommandController.java
  src/main/java/konkuk/thip/comment/adapter/in/web/request/CommentCreateRequest.java
  src/main/java/konkuk/thip/comment/adapter/in/web/request/DummyRequest.java
  src/main/java/konkuk/thip/comment/adapter/in/web/response/CommentIdResponse.java
  src/main/java/konkuk/thip/comment/adapter/in/web/response/DummyResponse.java
  src/main/java/konkuk/thip/comment/adapter/out/jpa/CommentJpaEntity.java
  src/main/java/konkuk/thip/comment/adapter/out/mapper/CommentMapper.java
  src/main/java/konkuk/thip/comment/adapter/out/persistence/CommentCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/comment/adapter/out/persistence/CommentQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/comment/application/port/in/CommentCreateUseCase.java
  src/main/java/konkuk/thip/comment/application/port/in/DummyUseCase.java
  src/main/java/konkuk/thip/comment/application/port/in/dto/CommentCreateCommand.java
  src/main/java/konkuk/thip/comment/application/port/in/dto/DummyCommand.java
  src/main/java/konkuk/thip/comment/application/port/out/CommentCommandPort.java
  src/main/java/konkuk/thip/comment/application/port/out/CommentQueryPort.java
  src/main/java/konkuk/thip/comment/application/service/CommentCreateService.java
  src/main/java/konkuk/thip/comment/application/service/CommentService.java
  src/main/java/konkuk/thip/comment/domain/Comment.java
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/common/post/CommentCountUpdatable.java
  src/main/java/konkuk/thip/common/post/PostType.java
  src/main/java/konkuk/thip/feed/domain/Feed.java
  src/main/java/konkuk/thip/record/adapter/out/jpa/RecordJpaEntity.java
  src/main/java/konkuk/thip/record/adapter/out/persistence/RecordCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/record/application/port/out/RecordCommandPort.java
  src/main/java/konkuk/thip/record/domain/Record.java
  src/main/java/konkuk/thip/room/domain/service/RoomParticipantService.java
  src/main/java/konkuk/thip/vote/adapter/out/jpa/VoteJpaEntity.java
  src/main/java/konkuk/thip/vote/adapter/out/persistence/VoteCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/vote/application/port/out/VoteCommandPort.java
  src/main/java/konkuk/thip/vote/domain/Vote.java
  src/test/java/konkuk/thip/comment/adapter/in/web/CommentControllerTest.java
  src/test/java/konkuk/thip/comment/adapter/in/web/CommentCreateAPITest.java
  src/test/java/konkuk/thip/comment/domain/CommentTest.java
  src/test/java/konkuk/thip/common/util/TestEntityFactory.java
  src/test/java/konkuk/thip/feed/adapter/in/web/FeedUpdateControllerTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomCloseJoinApiTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomGetHomeJoinedRoomsApiTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomGetMemberListApiTest.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomJoinApiTest.java
Labels: 🐶 희진, 🛠️ feat

#105 [fix] 기록장 조회 api 수정
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/common/post/PostType.java
  src/main/java/konkuk/thip/common/util/Cursor.java
  src/main/java/konkuk/thip/post/adapter/out/persistence/PostLikeJpaRepository.java
  src/main/java/konkuk/thip/post/adapter/out/persistence/PostLikeQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/post/application/port/out/PostLikeQueryPort.java
  src/main/java/konkuk/thip/record/adapter/in/web/RecordQueryController.java
  src/main/java/konkuk/thip/record/adapter/in/web/response/RecordDto.java
  src/main/java/konkuk/thip/record/adapter/in/web/response/RecordSearchResponse.java
  src/main/java/konkuk/thip/record/adapter/in/web/response/VoteDto.java
  src/main/java/konkuk/thip/record/adapter/out/persistence/RecordQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/record/adapter/out/persistence/RecordSearchTypeParams.java
  src/main/java/konkuk/thip/record/adapter/out/persistence/constants/SortType.java
  src/main/java/konkuk/thip/record/adapter/out/persistence/repository/RecordQueryRepository.java
  src/main/java/konkuk/thip/record/adapter/out/persistence/repository/RecordQueryRepositoryImpl.java
  src/main/java/konkuk/thip/record/application/port/in/dto/RecordSearchQuery.java
  src/main/java/konkuk/thip/record/application/port/in/dto/RecordSearchResult.java
  src/main/java/konkuk/thip/record/application/port/in/dto/RecordSearchUseCase.java
  src/main/java/konkuk/thip/record/application/port/out/RecordQueryPort.java
  src/main/java/konkuk/thip/record/application/port/out/dto/PostQueryDto.java
  src/main/java/konkuk/thip/record/application/service/RecordSearchService.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/RoomParticipantJpaEntity.java
  src/main/java/konkuk/thip/vote/adapter/out/persistence/VoteCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/vote/adapter/out/persistence/VoteQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/vote/adapter/out/persistence/repository/VoteQueryRepository.java
  src/main/java/konkuk/thip/vote/adapter/out/persistence/repository/VoteQueryRepositoryImpl.java
  src/main/java/konkuk/thip/vote/application/port/out/VoteCommandPort.java
  src/main/java/konkuk/thip/vote/application/port/out/VoteQueryPort.java
  src/main/java/konkuk/thip/vote/application/port/out/dto/VoteItemQueryDto.java
  src/main/java/konkuk/thip/vote/domain/VoteItem.java
  src/test/java/konkuk/thip/record/adapter/in/web/RecordQueryControllerTest.java
  src/test/java/konkuk/thip/record/adapter/in/web/RecordSearchApiTest.java
  src/test/java/konkuk/thip/record/adapter/out/persistence/RecordQueryRepositoryImplTest.java
  src/test/java/konkuk/thip/record/application/service/RecordSearchServiceTest.java
  src/test/java/konkuk/thip/vote/domain/VoteItemTest.java
Labels: 🍀 refactor, ⚡️ fix, 🧸 현준

#106 [feat] 팔로잉 조회 여부 api 개발
  src/main/java/konkuk/thip/user/adapter/in/web/UserQueryController.java
  src/main/java/konkuk/thip/user/adapter/in/web/response/UserIsFollowingResponse.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/FollowingJpaEntity.java
  src/main/java/konkuk/thip/user/adapter/out/jpa/UserJpaEntity.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/FollowingCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/user/adapter/out/persistence/repository/following/FollowingQueryRepositoryImpl.java
  src/main/java/konkuk/thip/user/application/mapper/FollowQueryMapper.java
  src/main/java/konkuk/thip/user/application/port/in/UserIsFollowingUsecase.java
  src/main/java/konkuk/thip/user/application/port/out/FollowingCommandPort.java
  src/main/java/konkuk/thip/user/application/service/UserIsFollowingService.java
  src/main/java/konkuk/thip/user/application/service/following/UserFollowService.java
  src/main/java/konkuk/thip/user/application/service/following/UserGetFollowService.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserFollowApiTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserIsFollowingApiTest.java
  src/test/java/konkuk/thip/user/application/service/UserFollowServiceTest.java
Labels: ⚡️ fix, 🛠️ feat, 🧸 현준

#116 [feat] 최근검색어 조회/삭제 api 구현
  src/main/java/konkuk/thip/book/application/service/BookSearchService.java
  src/main/java/konkuk/thip/common/entity/BaseDomainEntity.java
  src/main/java/konkuk/thip/common/entity/BaseJpaEntity.java
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/common/swagger/SwaggerResponseDescription.java
  src/main/java/konkuk/thip/feed/adapter/out/jpa/FeedJpaEntity.java
  src/main/java/konkuk/thip/recentSearch/adapter/in/web/RecentSearchCommandController.java
  src/main/java/konkuk/thip/recentSearch/adapter/in/web/RecentSearchQueryController.java
  src/main/java/konkuk/thip/recentSearch/adapter/in/web/response/DummyResponse.java
  src/main/java/konkuk/thip/recentSearch/adapter/in/web/response/RecentSearchGetResponse.java
  src/main/java/konkuk/thip/recentSearch/adapter/out/jpa/RecentSearchJpaEntity.java
  src/main/java/konkuk/thip/recentSearch/adapter/out/jpa/RecentSearchType.java
  src/main/java/konkuk/thip/recentSearch/adapter/out/jpa/SearchType.java
  src/main/java/konkuk/thip/recentSearch/adapter/out/mapper/RecentSearchMapper.java
  src/main/java/konkuk/thip/recentSearch/adapter/out/persistence/RecentSearchCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/recentSearch/adapter/out/persistence/RecentSearchQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/recentSearch/adapter/out/persistence/repository/RecentSearchJpaRepository.java
  src/main/java/konkuk/thip/recentSearch/adapter/out/persistence/repository/RecentSearchQueryRepository.java
  src/main/java/konkuk/thip/recentSearch/adapter/out/persistence/repository/RecentSearchQueryRepositoryImpl.java
  src/main/java/konkuk/thip/recentSearch/application/RecentSearchQueryMapper.java
  src/main/java/konkuk/thip/recentSearch/application/port/in/DummyUseCase.java
  src/main/java/konkuk/thip/recentSearch/application/port/in/RecentSearchDeleteUseCase.java
  src/main/java/konkuk/thip/recentSearch/application/port/in/RecentSearchGetUseCase.java
  src/main/java/konkuk/thip/recentSearch/application/port/out/RecentSearchCommandPort.java
  src/main/java/konkuk/thip/recentSearch/application/port/out/RecentSearchQueryPort.java
  src/main/java/konkuk/thip/recentSearch/application/service/RecentSearchDeleteService.java
  src/main/java/konkuk/thip/recentSearch/application/service/RecentSearchGetService.java
  src/main/java/konkuk/thip/recentSearch/application/service/RecentSearchService.java
  src/main/java/konkuk/thip/recentSearch/application/service/manager/RecentSearchCreateManager.java
  src/main/java/konkuk/thip/recentSearch/domain/RecentSearch.java
  src/main/java/konkuk/thip/user/application/service/UserSearchService.java
  src/main/java/konkuk/thip/user/application/service/following/UserFollowService.java
  src/main/java/konkuk/thip/user/domain/Following.java
  src/main/java/konkuk/thip/user/domain/User.java
  src/test/java/konkuk/thip/book/adapter/in/web/BookQueryControllerTest.java
  src/test/java/konkuk/thip/recentSearch/adapter/in/web/RecentSearchDeleteApiTest.java
  src/test/java/konkuk/thip/recentSearch/adapter/in/web/RecentSearchGetApiTest.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserSearchApiTest.java
  src/test/java/konkuk/thip/user/application/service/UserFollowServiceTest.java
  src/test/java/konkuk/thip/user/domain/FollowingTest.java
Labels: 🛠️ feat, 🧸 현준
