Repository THIP-TextHip/THIP-Server, pull requests merged in 2025-09, with the labels that each got.

#285 [infra] flyway 기반 DB 마이그레이션 도입 & Room 테이블에 RoomStatus 컬럼 추가
  build.gradle
  src/main/java/konkuk/thip/room/adapter/out/jpa/RoomJpaEntity.java
  src/main/java/konkuk/thip/room/adapter/out/jpa/RoomStatus.java
  src/main/java/konkuk/thip/room/adapter/out/mapper/RoomMapper.java
  src/main/java/konkuk/thip/room/domain/Room.java
  src/main/resources/db/migration/V1__BaseLine.sql
  src/main/resources/db/migration/V250828__Add_room_status.sql
Labels: 🍀 refactor, 🧸 현준, 🌈 infra

#291 [hotfix] 내가 참여한 모임방 api 의 영속성 코드 수정
  src/main/java/konkuk/thip/room/adapter/out/persistence/RoomQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/repository/RoomQueryRepository.java
  src/main/java/konkuk/thip/room/adapter/out/persistence/repository/RoomQueryRepositoryImpl.java
  src/main/java/konkuk/thip/room/application/port/out/dto/RoomQueryDto.java
  src/test/java/konkuk/thip/room/adapter/in/web/RoomShowMineApiTest.java
Labels: 👻 성준, 🔥 hotfix

#305 [feat] 알림센터 조회 api 개발
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/common/swagger/SwaggerResponseDescription.java
  src/main/java/konkuk/thip/notification/adapter/in/web/NotificationCommandController.java
  src/main/java/konkuk/thip/notification/adapter/in/web/NotificationQueryController.java
  src/main/java/konkuk/thip/notification/adapter/in/web/response/NotificationShowResponse.java
  src/main/java/konkuk/thip/notification/adapter/out/jpa/NotificationJpaEntity.java
  src/main/java/konkuk/thip/notification/adapter/out/mapper/NotificationMapper.java
  src/main/java/konkuk/thip/notification/adapter/out/persistence/NotificationQueryPersistenceAdapter.java
  src/main/java/konkuk/thip/notification/adapter/out/persistence/function/PrimaryKeyNotificationQueryFunction.java
  src/main/java/konkuk/thip/notification/adapter/out/persistence/repository/NotificationJpaRepository.java
  src/main/java/konkuk/thip/notification/adapter/out/persistence/repository/NotificationQueryRepository.java
  src/main/java/konkuk/thip/notification/adapter/out/persistence/repository/NotificationQueryRepositoryImpl.java
  src/main/java/konkuk/thip/notification/application/mapper/NotificationQueryMapper.java
  src/main/java/konkuk/thip/notification/application/port/in/NotificationShowUseCase.java
  src/main/java/konkuk/thip/notification/application/port/in/dto/NotificationType.java
  src/main/java/konkuk/thip/notification/application/port/in/fcm/FcmDeleteUseCase.java
  src/main/java/konkuk/thip/notification/application/port/in/fcm/FcmEnableStateChangeUseCase.java
  src/main/java/konkuk/thip/notification/application/port/in/fcm/FcmRegisterUseCase.java
  src/main/java/konkuk/thip/notification/application/port/out/NotificationQueryPort.java
  src/main/java/konkuk/thip/notification/application/port/out/dto/NotificationQueryDto.java
  src/main/java/konkuk/thip/notification/application/service/NotificationShowService.java
  src/main/java/konkuk/thip/notification/application/service/NotificationSyncExecutor.java
  src/main/java/konkuk/thip/notification/application/service/fcm/FcmDeleteService.java
  src/main/java/konkuk/thip/notification/application/service/fcm/FcmEnableStateChangeService.java
  src/main/java/konkuk/thip/notification/application/service/fcm/FcmRegisterService.java
  src/main/java/konkuk/thip/notification/application/service/template/NotificationTemplate.java
  src/main/java/konkuk/thip/notification/application/service/template/feed/FeedCommentLikedTemplate.java
  src/main/java/konkuk/thip/notification/application/service/template/feed/FeedCommentedTemplate.java
  src/main/java/konkuk/thip/notification/application/service/template/feed/FeedLikedTemplate.java
  src/main/java/konkuk/thip/notification/application/service/template/feed/FeedRepliedTemplate.java
  src/main/java/konkuk/thip/notification/application/service/template/feed/FollowedTemplate.java
  src/main/java/konkuk/thip/notification/application/service/template/feed/FolloweeNewPostTemplate.java
  src/main/java/konkuk/thip/notification/application/service/template/room/RoomActivityStartedTemplate.java
  src/main/java/konkuk/thip/notification/application/service/template/room/RoomCommentLikedTemplate.java
  src/main/java/konkuk/thip/notification/application/service/template/room/RoomJoinToHostTemplate.java
  src/main/java/konkuk/thip/notification/application/service/template/room/RoomPostCommentRepliedTemplate.java
  src/main/java/konkuk/thip/notification/application/service/template/room/RoomPostCommentedTemplate.java
  src/main/java/konkuk/thip/notification/application/service/template/room/RoomPostLikedTemplate.java
  src/main/java/konkuk/thip/notification/application/service/template/room/RoomRecordCreatedTemplate.java
  src/main/java/konkuk/thip/notification/application/service/template/room/RoomRecruitClosedEarlyTemplate.java
  src/main/java/konkuk/thip/notification/application/service/template/room/RoomVoteStartedTemplate.java
  src/main/java/konkuk/thip/notification/domain/Notification.java
  src/main/java/konkuk/thip/room/adapter/in/web/RoomQueryController.java
  src/main/java/konkuk/thip/room/application/port/in/RoomShowMineUseCase.java
  src/main/java/konkuk/thip/room/application/service/RoomShowMineService.java
  src/main/resources/db/migration/V250916__Add_notification_category.sql
  src/test/java/konkuk/thip/common/util/TestEntityFactory.java
  src/test/java/konkuk/thip/notification/adapter/in/web/NotificationShowApiTest.java
  src/test/java/konkuk/thip/notification/application/service/NotificationSyncExecutorTest.java
Labels: 🛠️ feat, 👻 성준

#307 [refactor] 소셜 로그인 동적 리다이렉트되도록 변경
  src/main/java/konkuk/thip/common/exception/code/ErrorCode.java
  src/main/java/konkuk/thip/common/security/constant/AuthParameters.java
  src/main/java/konkuk/thip/common/security/filter/JwtAuthenticationEntryPoint.java
  src/main/java/konkuk/thip/common/security/oauth2/CustomSuccessHandler.java
  src/main/java/konkuk/thip/common/security/oauth2/LoginTokenStorage.java
  src/main/java/konkuk/thip/common/security/oauth2/auth/AuthController.java
  src/main/java/konkuk/thip/common/security/oauth2/tokenstorage/LoginTokenStorage.java
  src/main/java/konkuk/thip/common/security/oauth2/tokenstorage/MemoryLoginTokenStorage.java
  src/main/java/konkuk/thip/common/security/oauth2/tokenstorage/RedisLoginTokenStorage.java
  src/main/java/konkuk/thip/common/security/resolver/AuthTokenArgumentResolver.java
  src/main/java/konkuk/thip/common/security/resolver/CustomAuthorizationRequestResolver.java
  src/main/java/konkuk/thip/common/security/resolver/Oauth2IdArgumentResolver.java
  src/main/java/konkuk/thip/common/security/resolver/UserIdArgumentResolver.java
  src/main/java/konkuk/thip/config/SecurityConfig.java
  src/main/java/konkuk/thip/config/WebMvcConfig.java
  src/main/java/konkuk/thip/config/properties/WebDomainProperties.java
  src/test/java/konkuk/thip/user/adapter/in/web/UserVerifyNicknameControllerTest.java
Labels: 🍀 refactor, 🧸 현준

#315 [refactor] 알림 리다이렉트를 위한 데이터 구조 수정
  src/main/java/konkuk/thip/comment/application/service/CommentCreateService.java
  src/main/java/konkuk/thip/comment/application/service/CommentLikeService.java
  src/main/java/konkuk/thip/notification/application/port/in/RoomNotificationOrchestrator.java
  src/main/java/konkuk/thip/notification/application/service/RoomNotificationOrchestratorSyncImpl.java
  src/main/java/konkuk/thip/notification/domain/value/MessageRoute.java
  src/main/java/konkuk/thip/post/adapter/out/persistence/PostLikeCommandPersistenceAdapter.java
  src/main/java/konkuk/thip/post/application/service/PostLikeService.java
  src/main/java/konkuk/thip/roompost/application/service/RoomPostSearchService.java
  src/test/java/konkuk/thip/notification/application/service/RoomNotificationOrchestratorSyncImplTest.java
  src/test/java/konkuk/thip/notification/application/service/RoomNotificationOrchestratorSyncImplUnitTest.java
Labels: 🍀 refactor, 👻 성준
